language: node_js
dist: focal
node_js:
  - "16"

cache:
  directories:
    - node_modules

before_install:
  - nvm install 16
  - nvm use 16
  - which node
  - node -v

install:
  - yarn install

script:
  - yarn test

notifications:
  email:
    recipients:
      - mireya08.jav@gmail.com
    on_success: change
    on_failure: always

after_success:
  - echo "Tests passed successfully!"
after_failure:
  - echo "Tests failed."

