name: Nodo CI
language: node_js
dist: focal
node_js:
  - "18"  # Cambiado de 16 a 18

cache:
  directories:
    - node_modules

before_install:
  - nvm install 18  # Cambiado de 16 a 18
  - nvm use 18      # Cambiado de 16 a 18
  - which node
  - node -v

install:
  - yarn install

script:
  - yarn test --reset-cache

notifications:
  email:
    recipients:
      - mireya08.jav@gmail.com
    on_success: change
    on_failure: always

after_success:
  - echo "Tests passed successfully!"
after_failure:
  - echo "Tests failed."


