name: Travis CI

language: node_js
node_js:
  - 18
dist: focal

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - nvm install 18
  - nvm use 18
  - which node
  - node -v

install:
  - yarn install

script:
  - yarn test --clearCache
  - yarn lint

notifications:
  email:
    recipients:
      - mireya08.jav@gmail.com
    on_success: never
    on_failure: always

after_success:
  - echo "Tests passed successfully!"

deploy:
  provider: script
  script: amplify publish
  skip_cleanup: true
  on:
    branch: main
