version: 0.2
install:
    runtime-versions:
      nodejs: 16
      commands:
      - npm install
      
phases:
  pre_build:
    commands:
      - npm install --global yarn

  build:
    commands:
      - yarn install 
      - yarn lint

on_success:
  commands:
    - echo "Tests passed successfully!"

on_failure:
  commands:
    - echo "Tests failed."

cache:
  paths:
    - node_modules/
